name: Build release artifacts
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  compile:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      # - run: sudo apt-get update && sudo apt-get install -y libglfw3-dev
      - run: zig build -Doptimize=ReleaseSafe
      - uses: actions/upload-artifact@v4
        with:
          name: zglgen-${{ matrix.os }}
          path: ./zig-out/bin/zglgen*
