name: Zig run check CI
on:
  push:
    paths:
      - '**/*.zig'
  pull_request:
    paths:
      - '**/*.zig'
  workflow_dispatch:

concurency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: zig build -Doptimize=ReleaseSafe
      - run: ./zig-out/bin/zglgen --api gl:4.6 --output ./zig-out/gen.zig GL_KHR_debug

    
