name: Zig CI
on:
  push:
    paths:
      - 'src/**/*.zig'
      - 'build.zig'
      - 'build.zig.zon'
  pull_request:
    paths:
      - 'src/**/*.zig'
      - 'build.zig'
      - 'build.zig.zon'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build -Dbuild-examples=false
      # check for runtime errors and panics
      - run: ./zig-out/bin/zglgen --api gl:4.6 --output ./zig-out/gen.zig GL_KHR_debug
      - run: ./zig-out/bin/zglgen --api gles1:1.0 --output ./zig-out/gen.zig GL_KHR_debug
      - run: ./zig-out/bin/zglgen --api gles2:3.0 --output ./zig-out/gen.zig GL_KHR_debug
      - run: ./zig-out/bin/zglgen --api glsc1:2.0 --output ./zig-out/gen.zig GL_KHR_debug
  compile-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build -Dbuild-examples=false -Doptimize=ReleaseSafe
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig fmt --check src/*.zig
