name: Zig CI
on:
  push:
    paths:
      - '**/*.zig'
  pull_request:
    paths:
      - '**/*.zig'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: sudo apt-get update && sudo apt-get install -y libglfw3-dev
      - run: zig build
  compile-release:
    needs: compile # don't compile if debug already failed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: sudo apt-get update && sudo apt-get install -y libglfw3-dev
      - run: zig build -Doptimize=ReleaseSafe
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: sudo apt-get update && sudo apt-get install -y libglfw3-dev
      - run: zig fmt --check src/*.zig
  test-generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: sudo apt-get update && sudo apt-get install -y libglfw3-dev
      - run: zig build -Doptimize=ReleaseSafe
      - run: ./zig-out/bin/zglgen --api gl:4.6 --output ./zig-out/gen.zig GL_KHR_debug
